<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<AssemblyName>KL</AssemblyName>
		<LangVersion>latest</LangVersion>
		<!-- 启用XML文档生成 -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Projectiles\FireWind.png" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="ActionsSystem\TemplateActions\" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="BossChecklist">
	    <HintPath>..\BossChecklist.dll</HintPath>
	  </Reference>
	  <Reference Include="FargowiltasSouls">
	    <HintPath>FargowiltasSouls.dll</HintPath>
	  </Reference>
	  <Reference Include="Lights">
	    <HintPath>..\Lights.dll</HintPath>
	  </Reference>
	  <Reference Include="SilkyUIFramework">
	    <HintPath>..\SilkyUIFramework.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<!-- References -->

</Project>